# Generated by Django 2.2.1 on 2019-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20190607_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='issues/{title}'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.FileField(blank=True, null=True, upload_to='issues/{title}'),
        ),
    ]
